version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: worldcup2022
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  backend_app:
    build: backend_app/
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5000:5000"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    depends_on:
      - db
  flutter_app:
    build: flutter_app/
    ports:
      - "1200:80"
    depends_on:
      - backend_app
